import type { RouteItem, Category, RouteStats } from './types';

export const MOCK_CATEGORIES: Category[] = [
  { id: 1, name: 'Road Bike', icon: 'bike', sort_order: 1 },
  { id: 2, name: 'MTB', icon: 'mtb', sort_order: 2 },
  { id: 3, name: 'Gravel', icon: 'gravel', sort_order: 3 },
  { id: 4, name: 'Trekking', icon: 'trekking', sort_order: 4 },
  { id: 5, name: 'Hiking', icon: 'hiking', sort_order: 5 },
  { id: 6, name: 'Bikepacking', icon: 'bikepacking', sort_order: 6 },
  { id: 7, name: 'Motorbike - Adventure', icon: 'moto', sort_order: 7 },
  { id: 8, name: 'Alpine', icon: 'alpine', sort_order: 8 },
];

export const MOCK_ROUTES: RouteItem[] = [
  {
    id: 1,
    title: 'Alpine Forest MTB Trail — Innsbruck',
    description: 'An incredible MTB descent through alpine forests near Innsbruck. Starting from the Nordkette cable car station, the trail winds through dense pine forests with breathtaking views of the Inn Valley. The route covers challenging single-track sections with technical rock gardens and root passages. Perfect for experienced mountain bikers looking for an adrenaline-packed ride.',
    price: 12.99,
    category_id: 2,
    category_name: 'MTB',
    creator_name: 'AlpineRider',
    cover_image_key: 'https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?w=600&h=400&fit=crop',
    location_string: 'Innsbruck, Tyrol, Austria',
    latitude: 47.2692,
    longitude: 11.4041,
    distance_km: 24.5,
    elevation_gain_m: 1200,
    estimated_time_h: 3.5,
    difficulty: 'hard',
    surface_type: 'dirt',
    season: 'summer',
    loop_type: 'loop',
    start_point: 'Nordkette Cable Car',
    end_point: 'Innsbruck Old Town',
    created_at: '2026-03-10T10:00:00Z',
    user_id: 'user-1',
  },
  {
    id: 2,
    title: 'Himalayan Motorcycle Adventure — Ladakh',
    description: 'The ultimate motorcycle adventure through the Himalayas. This route takes you over some of the highest motorable passes in the world, including Khardung La at 5,359m. Experience the raw beauty of Ladakh with its dramatic landscapes, ancient monasteries, and warm local hospitality.',
    price: 24.99,
    category_id: 7,
    category_name: 'Motorbike - Adventure',
    creator_name: 'MotoNomad',
    cover_image_key: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=400&fit=crop',
    location_string: 'Leh, Ladakh, India',
    latitude: 34.1526,
    longitude: 77.5771,
    distance_km: 420,
    elevation_gain_m: 8500,
    estimated_time_h: 48,
    difficulty: 'expert',
    surface_type: 'mixed',
    season: 'summer',
    loop_type: 'point-to-point',
    created_at: '2026-03-08T14:00:00Z',
    user_id: 'user-2',
  },
  {
    id: 3,
    title: 'Dolomites Ridge Trekking — Alta Via 1',
    description: 'A stunning ridge trek through the Italian Dolomites following parts of the legendary Alta Via 1. The route offers spectacular views of iconic peaks like Tre Cime di Lavaredo and dramatic rock formations. Includes overnight stays in mountain refuges.',
    price: 18.50,
    category_id: 4,
    category_name: 'Trekking',
    creator_name: 'DolomiteHiker',
    cover_image_key: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&h=400&fit=crop',
    location_string: 'Cortina d\'Ampezzo, Veneto, Italy',
    latitude: 46.5369,
    longitude: 12.1357,
    distance_km: 65,
    elevation_gain_m: 4200,
    estimated_time_h: 32,
    difficulty: 'hard',
    surface_type: 'rocky',
    season: 'summer',
    loop_type: 'point-to-point',
    created_at: '2026-03-05T09:00:00Z',
    user_id: 'user-3',
  },
  {
    id: 4,
    title: 'Algarve Coastal Trail Running',
    description: 'A breathtaking trail running route along the rugged coastline of Portugal\'s Algarve region. Run past dramatic sea cliffs, hidden beaches, and picturesque fishing villages. The Seven Hanging Valleys trail is a highlight.',
    price: 9.99,
    category_id: 4,
    category_name: 'Trekking',
    creator_name: 'CoastalRunner',
    cover_image_key: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&h=400&fit=crop',
    location_string: 'Faro, Algarve, Portugal',
    latitude: 37.0194,
    longitude: -7.9304,
    distance_km: 18,
    elevation_gain_m: 450,
    estimated_time_h: 2.5,
    difficulty: 'moderate',
    surface_type: 'mixed',
    season: 'year-round',
    loop_type: 'out-and-back',
    created_at: '2026-03-01T08:00:00Z',
    user_id: 'user-4',
  },
  {
    id: 5,
    title: 'Moab Red Rock MTB — Slickrock Trail',
    description: 'The iconic Slickrock Trail in Moab, Utah. This legendary mountain biking trail takes you over petrified sand dunes with incredible grip and stunning views of the Colorado River and La Sal Mountains.',
    price: 14.99,
    category_id: 2,
    category_name: 'MTB',
    creator_name: 'DesertRider',
    cover_image_key: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600&h=400&fit=crop',
    location_string: 'Moab, Utah, USA',
    latitude: 38.5733,
    longitude: -109.5498,
    distance_km: 19.3,
    elevation_gain_m: 580,
    estimated_time_h: 3,
    difficulty: 'hard',
    surface_type: 'rocky',
    season: 'spring',
    loop_type: 'loop',
    created_at: '2026-02-28T12:00:00Z',
    user_id: 'user-5',
  },
  {
    id: 6,
    title: 'Transfăgărășan Motorcycle Pass',
    description: 'One of the most spectacular mountain roads in Europe. The Transfăgărășan highway in Romania winds through the Carpathian Mountains with hairpin turns, tunnels, and views of Bâlea Lake glacier.',
    price: 15.99,
    category_id: 7,
    category_name: 'Motorbike - Adventure',
    creator_name: 'EuroMotoTour',
    cover_image_key: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop',
    location_string: 'Argeș, Romania',
    latitude: 45.6035,
    longitude: 24.6152,
    distance_km: 151,
    elevation_gain_m: 3200,
    estimated_time_h: 6,
    difficulty: 'moderate',
    surface_type: 'paved',
    season: 'summer',
    loop_type: 'point-to-point',
    created_at: '2026-02-25T15:00:00Z',
    user_id: 'user-6',
  },
  {
    id: 7,
    title: 'Amalfi Coast Road Cycling',
    description: 'A classic road cycling route along Italy\'s famous Amalfi Coast. Climb through terraced lemon groves, descend to charming coastal villages, and enjoy the stunning Mediterranean views from every bend.',
    price: 11.50,
    category_id: 1,
    category_name: 'Road Bike',
    creator_name: 'ItalianCyclist',
    cover_image_key: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=600&h=400&fit=crop',
    location_string: 'Amalfi, Campania, Italy',
    latitude: 40.6340,
    longitude: 14.6027,
    distance_km: 52,
    elevation_gain_m: 1800,
    estimated_time_h: 4,
    difficulty: 'moderate',
    surface_type: 'paved',
    season: 'spring',
    loop_type: 'out-and-back',
    created_at: '2026-02-20T11:00:00Z',
    user_id: 'user-7',
  },
  {
    id: 8,
    title: 'Borneo Jungle Hiking — Kinabalu Park',
    description: 'An immersive hiking experience through the ancient rainforests of Borneo. The trail leads through lush jungle, past waterfalls and canopy walkways, with opportunities to spot orangutans and rare birds.',
    price: 16.99,
    category_id: 5,
    category_name: 'Hiking',
    creator_name: 'JungleTrekker',
    cover_image_key: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&h=400&fit=crop',
    location_string: 'Sabah, Borneo, Malaysia',
    latitude: 6.0753,
    longitude: 116.5585,
    distance_km: 12,
    elevation_gain_m: 800,
    estimated_time_h: 5,
    difficulty: 'moderate',
    surface_type: 'dirt',
    season: 'year-round',
    loop_type: 'loop',
    created_at: '2026-02-15T07:00:00Z',
    user_id: 'user-8',
  },
];

export const MOCK_STATS: Record<number, RouteStats> = {
  1: { average_rating: 4.8, total_ratings: 23, total_purchases: 45 },
  2: { average_rating: 4.9, total_ratings: 15, total_purchases: 32 },
  3: { average_rating: 4.7, total_ratings: 31, total_purchases: 67 },
  4: { average_rating: 4.5, total_ratings: 12, total_purchases: 28 },
  5: { average_rating: 4.6, total_ratings: 42, total_purchases: 89 },
  6: { average_rating: 4.4, total_ratings: 18, total_purchases: 41 },
  7: { average_rating: 4.8, total_ratings: 27, total_purchases: 54 },
  8: { average_rating: 4.3, total_ratings: 9, total_purchases: 19 },
};
